chassor_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ChassorCoreBundle:Default:index }


#-- pages diverses -----------------------------

index:
    pattern:  /
    defaults: { _controller: ChassorCoreBundle:Default:index }

index2:
    pattern:  /index
    defaults: { _controller: ChassorCoreBundle:Default:index }

apropos:
    pattern:  /apropos
    defaults: { _controller: ChassorCoreBundle:Default:apropos }

activation:
    pattern:  /activation
    defaults: { _controller: ChassorCoreBundle:Banque:activation }



#-- Les enigmes -----------------------------

enigmes:
    pattern:  /enigmes
    defaults: { _controller: ChassorCoreBundle:Enigme:enigmes }

enigme:
    path:      /enigme-{code}
    defaults:  { _controller: ChassorCoreBundle:Enigme:enigme }

enigmeX:       # validation enigme double
    path:      /enigmeX-{code}
    defaults:  { _controller: ChassorCoreBundle:Enigme:enigmeX }

enigmeImage:
    path:      /enigmes/{code}-{image_id}.jpg
    defaults:  { _controller: ChassorCoreBundle:Enigme:enigmeImage }

indiceAchat:
    path:      /enigmes/achat-indice-{code}-{indice}
    defaults:  { _controller: ChassorCoreBundle:Enigme:indiceAchat }

enigmeAchat:
    path:      /enigmes/achat-enigme-{code}
    defaults:  { _controller: ChassorCoreBundle:Enigme:enigmeAchat }


#-- La banque -----------------------------

banque:
    pattern:  /banque
    defaults: { _controller: ChassorCoreBundle:Banque:lister }

retour_paiement:
    pattern:  /ipn/retour-paiement-42-{user}-{trans}-{etat}
    defaults: { _controller: ChassorCoreBundle:Banque:retourPaiement }
