chassor_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ChassorCoreBundle:Default:index }


#-- pages diverses -----------------------------

index:
    pattern:  /
    defaults: { _controller: ChassorCoreBundle:Default:index }

index2:
    pattern:  /index
    defaults: { _controller: ChassorCoreBundle:Default:index }

apropos:
    pattern:  /apropos
    defaults: { _controller: ChassorCoreBundle:Default:apropos }

jouer:
    pattern:  /comment-jouer
    defaults: { _controller: ChassorCoreBundle:Default:jouer }

contact:
    pattern:  /contact
    defaults: { _controller: ChassorCoreBundle:Default:contact }

reglement:
    pattern:  /reglement
    defaults: { _controller: ChassorCoreBundle:Default:reglement }
    
partenaires:
    pattern:  /partenaires
    defaults: { _controller: ChassorCoreBundle:Default:partenaires }

#-- Les enigmes -----------------------------

enigmes:
    pattern:  /enigmes
    defaults: { _controller: ChassorCoreBundle:Enigme:enigmes }

enigme:
    path:      /enigme-{code}
    defaults:  { _controller: ChassorCoreBundle:Enigme:enigme }

enigmeX:       # validation enigme double
    path:      /enigmeX-{code}
    defaults:  { _controller: ChassorCoreBundle:Enigme:enigmeX }

enigmeImage:
    path:      /enigmes/{code}-{image_id}.jpg
    defaults:  { _controller: ChassorCoreBundle:Enigme:enigmeImage }

indiceAchat:
    path:      /enigmes/achat-indice-{code}-{indice}
    defaults:  { _controller: ChassorCoreBundle:Enigme:indiceAchat }

enigmeAchat:
    path:      /enigmes/achat-enigme-{code}
    defaults:  { _controller: ChassorCoreBundle:Enigme:enigmeAchat }


#-- La banque -----------------------------

banque:
    pattern:  /banque
    defaults: { _controller: ChassorCoreBundle:Banque:lister }

achat:
    pattern:  /banque/achat/{type}
    defaults: { _controller: ChassorCoreBundle:Banque:achatPieces }
    
partage:
    pattern:  /banque/partage/{type}
    defaults: { _controller: ChassorCoreBundle:Banque:partage }

retourPaiement:
    pattern:  /banque/retourPaiement
    defaults: { _controller: ChassorCoreBundle:Banque:retourPaiement }

