parameters:
#    core.example.class: Raf\ChassorCoreBundle\Example

services:
#    core.example:
#        class: %core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    core.registration.form.type:
        class: Raf\ChassorCoreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
        - { name: form.type, alias: chassor_user_registration }
        
    ocb.chaine:
        class: Raf\ChassorCoreBundle\OCB\OCBChaine
    ocb.enigme:
        class: Raf\ChassorCoreBundle\OCB\OCBEnigme
        arguments: [@doctrine.orm.entity_manager, @ocb.chaine]
    ocb.acces:
        class: Raf\ChassorCoreBundle\OCB\OCBAcces
        arguments: [@doctrine.orm.entity_manager]
    ocb.message:
        class: Raf\ChassorCoreBundle\OCB\OCBMessage
        arguments: [@doctrine.orm.entity_manager, @session]
        
    paypal_im_received:
        class: Raf\ChassorCoreBundle\Event\PaypalListener
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - { name: kernel.event_listener, event: paypal.ipn.receive, method: onIPNReceive }
            
#    forum_listener_login:
#        class: Raf\ChassorCoreBundle\Event\ForumLoginListener
#        arguments: [@widop_php_bb.authentication_manager]
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: onUserLogin }
#            - { name: kernel.event_listener, event: security.interactive_logout, method: onUserLogout }
            
#    forum_listener_register:
#        class: Raf\ChassorCoreBundle\Event\ForumRegisterListener
#        arguments: [@widop_php_bb.user_manager]
#        tags:
#            - { name: kernel.event_listener, event: fos_user.registration.completed, method: onUserRegister }




