parameters:
#    core.example.class: Raf\ChassorCoreBundle\Example

services:
#    core.example:
#        class: %core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    paypal_im_received:
        class: Raf\ChassorCoreBundle\Event\PaypalListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: paypal.ipn.receive, method: onIPNReceive }