parameters:
#    core.example.class: Raf\ChassorCoreBundle\Example

services:
#    core.example:
#        class: %core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    core.registration.form.type:
        class: Raf\ChassorCoreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
        - { name: form.type, alias: chassor_user_registration }
        
    ocb.enigme:
        class: Raf\ChassorCoreBundle\OCB\OCBEnigme
    ocb.acces:
        class: Raf\ChassorCoreBundle\OCB\OCBAcces
    ocb.message:
        class: Raf\ChassorCoreBundle\OCB\OCBMessage
        
    paypal_im_received:
        class: Raf\ChassorCoreBundle\Event\PaypalListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: paypal.ipn.receive, method: onIPNReceive }