admin_accueil:
    pattern:  /
    defaults: { _controller: ChassorAdminBundle:AdminChassor:lister }

admin_enigme_lister:
    pattern:  /enigmes
    defaults: { _controller: ChassorAdminBundle:AdminEnigme:lister }

admin_enigme_ajouter:
    pattern:  /enigme-ajout
    defaults: { _controller: ChassorAdminBundle:AdminEnigme:ajouter }

admin_enigme_modifier:
    pattern:  /enigmes/{id}
    defaults: { _controller: ChassorAdminBundle:AdminEnigme:modifier }

admin_indice_lister:
    pattern:  /indices
    defaults: { _controller: ChassorAdminBundle:AdminIndice:lister }

admin_indice_ajouter:
    pattern:  /indice-ajout
    defaults: { _controller: ChassorAdminBundle:AdminIndice:ajouter }

admin_indice_modifier:
    pattern:  /indices/{id}
    defaults: { _controller: ChassorAdminBundle:AdminIndice:modifier }

admin_transaction_lister:
    pattern:  /transactions
    defaults: { _controller: ChassorAdminBundle:AdminTransaction:lister }
    
admin_chassor_lister:
    pattern:  /chassors
    defaults: { _controller: ChassorAdminBundle:AdminChassor:lister }
    
