admin_accueil:
    pattern:  /
    defaults: { _controller: ChassorAdminBundle:Default:accueil }

admin_enigme_lister:
    pattern:  /enigmes
    defaults: { _controller: ChassorAdminBundle:AdminEnigme:lister }

admin_enigme_ajouter:
    pattern:  /enigmes/ajouter
    defaults: { _controller: ChassorAdminBundle:AdminEnigme:ajouter }

admin_enigme_supprimer:
    pattern:  enigmes/{id}/supprimer
    defaults: { _controller: ChassorAdminBundle:AdminEnigme:supprimer }

admin_enigme_modifier:
    pattern:  /enigmes/{id}/modifier
    defaults: { _controller: ChassorAdminBundle:AdminEnigme:modifier }

admin_indice_lister:
    pattern:  /indices
    defaults: { _controller: ChassorAdminBundle:AdminIndice:lister }

admin_indice_ajouter:
    pattern:  /indices/ajouter
    defaults: { _controller: ChassorAdminBundle:AdminIndice:ajouter }

admin_indice_modifier:
    pattern:  /indices/{id}/modifier
    defaults: { _controller: ChassorAdminBundle:AdminIndice:modifier }

admin_indice_supprimer:
    pattern:  /indices/{id}/supprimer
    defaults: { _controller: ChassorAdminBundle:AdminIndice:supprimer }

admin_transaction_lister:
    pattern:  /transactions
    defaults: { _controller: ChassorAdminBundle:AdminTransaction:lister }
    
admin_chassor_lister:
    pattern:  /chassors
    defaults: { _controller: ChassorAdminBundle:AdminChassor:lister }
    
admin_message_lister:
    pattern:  /messages
    defaults: { _controller: ChassorAdminBundle:AdminMessage:lister }

admin_message_ajouter:
    pattern:  /messages/ajouter
    defaults: { _controller: ChassorAdminBundle:AdminMessage:ajouter }

admin_message_modifier:
    pattern:  /messages/{id}/modifier
    defaults: { _controller: ChassorAdminBundle:AdminMessage:modifier }

admin_message_supprimer:
    pattern:  /messages/{id}/supprimer
    defaults: { _controller: ChassorAdminBundle:AdminMessage:supprimer }

admin_mail_lister:
    pattern:  /mails
    defaults: { _controller: ChassorAdminBundle:AdminMail:lister }

admin_mail_ajouter:
    pattern:  /mails/ajouter
    defaults: { _controller: ChassorAdminBundle:AdminMail:ajouter }

admin_mail_tester:
    pattern:  /mails/{id}/tester
    defaults: { _controller: ChassorAdminBundle:AdminMail:tester }

admin_mail_modifier:
    pattern:  /mails/{id}/modifier
    defaults: { _controller: ChassorAdminBundle:AdminMail:modifier }

admin_mail_envoyer:
    pattern:  /mail-envoi
    defaults: { _controller: ChassorAdminBundle:AdminMail:envoyer }
    