parameters:
#    chassor.example.class: Raf\ChassorBundle\Example

services:
#    chassor.example:
#        class: %chassor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    chassor_user_registration:
        class: Raf\ChassorUserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: chassor_user_registration }