<?php

namespace Raf\ChassorUserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChassorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChassorRepository extends EntityRepository
{
 
}
