<?php

namespace Raf\ChassorCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Raf\ChassorUserBundle\Entity\Chassor;

/**
 * ChassorEnigmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChassorEnigmeRepository extends EntityRepository
{
    public function findByChassor2(Chassor $chassor)
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb->leftJoin('a.enigme', 'en')
           ->addSelect('en');
           
        $qb->where('a.chassor = :chassor')
           ->setParameter('chassor', $chassor);
        
        return $qb->getQuery()->getResult();
    }
}
