<?php

namespace Raf\ChassorCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Raf\ChassorCoreBundle\Entity\Chassor;
use Raf\ChassorCoreBundle\Entity\ChassorEnigme;
use Raf\ChassorCoreBundle\Entity\Enigme;
use Raf\ChassorCoreBundle\Entity\Indice;

/**
 * ChassorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChassorRepository extends EntityRepository
{
    public function findAll2()
    {
        $qb = $this->createQueryBuilder('c')
                   ->leftJoin('c.transactions', 'ct')
                   ->addSelect('ct')
                   ->leftJoin('c.indices', 'ci')
                   ->addSelect('ci')
                   ->leftJoin('c.enigmes', 'ce')
                   ->addSelect('ce')
        ;
        
        return $qb->getQuery()->getResult();
    }
    
    public function findParrain($parrain)
    {
        $qb = $this->createQueryBuilder('c')
                   ->where('c.username = :parrain')
                   ->orWhere('c.email = :parrain')
                   ->setParameter('parrain', $parrain)
        ;
    
        return $qb->getQuery()->getSingleResult();
    }
}
