<?php

namespace Raf\ChassorCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * EnigmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnigmeRepository extends EntityRepository
{

    public function findNew($em, Chassor $chassor)
    {
        $query = $em->createQuery('SELECT e FROM ChassorCoreBundle:Enigme e 
                                   WHERE e NOT IN (
                                   SELECT IDENTITY(ce1.enigme) FROM ChassorCoreBundle:ChassorEnigme ce1
                                   WHERE ce1.chassor = :chassor)') 
                    ->setParameter('chassor', $chassor);
        
        return $query->getResult();
    }
}
