<?php

namespace Raf\ChassorCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Raf\ChassorCoreBundle\Entity\Chassor;


/**
 * IndiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndiceRepository extends EntityRepository
{
    public function findByChassor2(Chassor $chassor, Enigme $enigme)
    {
        $qb = $this->createQueryBuilder('i');
    
        $qb->where('i.enigme = :enigme')
           ->setParameter('enigme', $enigme);
        
        $qb->leftJoin('i.chassors', 'c', 'with', 'c = :chassor')
           ->setParameter('chassor', $chassor)
           ->addSelect('c');
 
        $qb->orderBy('i.ordre', 'asc');
    
        return $qb->getQuery()->getResult();
    }
    
    public function findAll2()
    {
        $qb = $this->createQueryBuilder('i');
    
        $qb->leftJoin('i.enigme', 'e');
 
        $qb->orderBy('e.code', 'asc');
        $qb->addOrderBy('i.ordre', 'asc');
    
        return $qb->getQuery()->getResult();
    }
}
