<?php

namespace Raf\ChassorCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Raf\ChassorCoreBundle\Entity\Chassor;


/**
 * IndiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndiceRepository extends EntityRepository
{
    public function findByChassor2(Chassor $chassor, Enigme $enigme)
    {
        $qb = $this->createQueryBuilder('i');
    
        $qb->where('i.enigme = :enigme')
           ->setParameter('enigme', $enigme);
        
        $qb->leftJoin('i.chassors', 'c', 'with', 'c = :chassor')
           ->setParameter('chassor', $chassor)
           ->addSelect('c');
    
        return $qb->getQuery()->getResult();
    }
}
