<?php

namespace Raf\ChassorCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Raf\ChassorCoreBundle\Entity\Chassor;
use Raf\ChassorCoreBundle\Entity\Message;


/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findByChassor2($em, Chassor $chassor)
    {
        $messagesArray = $chassor->getMessages()->toArray();
        
        $query = $em->createQuery(
                'SELECT
                    m
                 FROM
                    ChassorCoreBundle:Message m
                 WHERE
                    m.date <= :date
                 AND
                    m NOT IN (:messagesArray)
                 ORDER BY m.date ASC'); 
        
        $query->setParameter('date',    new \DateTime())
              ->setParameter('messagesArray', count($messagesArray) > 0 ? $messagesArray : '-1');
        
        return $query->getResult();
    }
}
