<?php

namespace Raf\ChassorAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GraphRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraphRepository extends EntityRepository
{
}
